autenticacao/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
app_name = 'autenticacao'

urlpatterns = [
    path('', views.login, name='login'),
    path("verificar_usuario/", views.verificar_usuario, name="verificar_usuario"),
    path("logout/", views.logout, name="logout"),
    path('password_reset/', views.MyPasswordReset.as_view(),name='password_reset'),
    path('password_reset/done/', views.MyPasswordResetDone.as_view(),name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',
        success_url=reverse_lazy('autenticacao:password_reset_complete')
        ),
        name='password_reset_confirm'),
    path('reset/complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),
    
]

cadastros/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'cadastros'

urlpatterns = [
    path('cadastro_usuario/', views.cadastro_usuario, name='cadastro_usuario'),
    path('oferta_carona/', views.oferta_carona, name='oferta_carona'),
    path('listar_caronas/', views.listar_caronas, name='listar_caronas')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('autenticacao.urls')),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
    path('cadastros/', include('cadastros.urls')),
]

core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [
    path("main", views.main, name="main"),
    path('cadastros/', include('cadastros.urls')),
]

autenticacao/models.py
from django.db import models

# Create your models here.

autenticacao/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http import JsonResponse
from django.urls import reverse_lazy
from cadastros.models import Usuario
from django.contrib.auth.views import PasswordResetView


        
def login(request):
    if request.method == 'POST':
        email = request.POST.get('txtEmail')
        senha = request.POST.get('txtSenha')

        try:
            usuario = Usuario.objects.get(email=email)  # Busca usuário pelo email
            usuario_autenticado = authenticate(request, username=usuario.email, password=senha)  
            
            if usuario_autenticado is not None:
                #limpa as sessoes do usuario
                request.session.flush()
                auth_login(request, usuario_autenticado)  # Faz login do usuário
                
                request.session['id_atual'] = usuario.id
                request.session['email_atual'] = usuario.email
                request.session['telefone'] = usuario.telefone
                #configura sessao para expirar em 4 horas
                request.session.set_expiry(14400)
                messages.success(request, 'Login realizado com sucesso.')
                return redirect('core:main')  # Redireciona para onde quiser
            else:
                messages.error(request, 'E-mail ou senha inválidos.')
        except Usuario.DoesNotExist:
            messages.error(request, 'Usuário não encontrado.')

    return render(request, 'login.html')

def logout(request):
    #limpa a sessao ao deslogar
    request.session.flush()
    auth_logout(request)
    
    messages.success(request, 'Logout realizado com sucesso.')
    return redirect('autenticacao:login')

class MyPasswordReset(PasswordResetView):
    template_name = 'password_reset_form.html'
    email_template_name = 'password_reset_email.html'
    subject_template_name = 'password_reset_subject.txt'
    success_url = reverse_lazy('autenticacao:password_reset_done')

class MyPasswordResetDone(PasswordResetView):
    template_name = 'password_reset_done.html'
    

def verificar_usuario(request):
    email = request.GET.get('email', '').strip()
        
    if Usuario.objects.filter(email=email).exists():
        return JsonResponse({'usuario_existe': True})
    else:
        return JsonResponse({'usuario_existe': False})

autenticacao/templates/login.html
{% extends 'index.html' %}

{% block conteudo %}
<div class="container mt-5">
    <h4 class="text-center mb-4">Login</h4>
    <form method="POST" action="{% url 'autenticacao:login' %}">
        {% csrf_token %}
        <div class="form-group" align="left" >
            <label for="txtEmail" a >E-mail</label>
            <input type="email" class="form-control" id="txtEmail" name="txtEmail" required autocomplete="off">
            <div id="divEmailError" class="error-message text-danger"> </div>
        </div>

        <div class="form-group hidden-group" align="left" id="divSenha">
            <label for="txtSenha">Senha</label>
            <input type="password" class="form-control" id="txtSenha" name="txtSenha" required autocomplete="new-password">
        </div>

        <div id="divSpace" class="space"></div>
        <button type="submit" class="btn btn-primary w-100">Entrar</button>
        <a href="{% url 'autenticacao:password_reset' %}" class="btn btn-light w-100 mt-2">Esqueci minha senha</a>
    </form>

    <!-- Botão de cadastro sempre visível -->
    <div class="mt-3 text-center">
        <p>Ainda não tem uma conta?</p>
        <a href="{% url 'cadastros:cadastro_usuario' %}" class="btn btn-success">Criar Conta</a>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#txtEmail').on('input', function() {
            var email = $(this).val().trim();
            $('#divSenha').addClass('hidden-group'); // Esconde a senha até confirmar o usuário
            $('#divEmailError').text('').removeClass('visible');

            if (email.length > 0) {
                $.ajax({
                    url: "{% url 'autenticacao:verificar_usuario' %}",
                    data: {'email': email},
                    success: function(data) {
                        if (data.usuario_existe) {
                            $('#divSenha').removeClass('hidden-group'); // Mostra o campo de senha
                        } else {
                            $('#divEmailError').text('E-mail não encontrado!').addClass('visible');
                        }
                    },
                    error: function() {
                        toastr.error("Erro ao verificar e-mail. Tente novamente.", "Erro");
                    }
                });
            }
        });
    });
</script>
{% endblock %}